# image will be published to ghcr.io/<user>/<name>
name: ostree-workstation
description: bluefix-dx (gnome) + sway and other stuff
base-image: ghcr.io/ublue-os/bluefin-dx
image-version: 39

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - usr: /usr # copies config/files/usr into your image's /usr.
                  # put configuration files you want in /etc/ on a booted system 
                  # in /usr/etc/ in the image. read more in files module reference.

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/wezfurlong/wezterm-nightly/repo/fedora-%OS_VERSION%/wezfurlong-wezterm-nightly-fedora-%OS_VERSION%.repo
    install:
      - sway-config-fedora
      - wezterm
      - krb5-workstation

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      install:
        - com.google.Chrome
        - com.logseq.Logseq
        - com.slack.Slack
        - com.spotify.Client
        - org.mozilla.firefox
        - com.visualstudio.code
        - org.gnome.DejaDup
        - org.localsend.localsend_app

  - type: script
    scripts:
      - get-apps.sh

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

